<?php

namespace Application\Controller;

use Zend\Mvc\MvcEvent;

class BaseAdminController extends BaseController
{
    public function onDispatch(MvcEvent $e)
    {
        if(! $this->identity()){
            return $this->redirect()->toRoute('auth-doctrine/default', array('controller' => 'index', 'action' => 'login'));
        }
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

}